apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eink-data
  namespace: eink
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: ""   # uncomment + set if your cluster doesn't have a default
