# Copy to secret.yaml, replace tokens with `openssl rand -hex 32` output, keep
# secret.yaml out of git (it's already in .gitignore).
apiVersion: v1
kind: Secret
metadata:
  name: eink-tokens
  namespace: eink
type: Opaque
stringData:
  push-token: "REPLACE-WITH-openssl-rand-hex-32"
  read-token: "REPLACE-WITH-openssl-rand-hex-32"
