; PlatformIO Project Configuration File
; Inkplate 10 (ESP32-WROVER-E, 4MB flash, 8MB PSRAM)

[env:inkplate10]
platform = espressif32
board = esp32dev
framework = arduino

upload_port = /dev/cu.usbserial-10
upload_speed = 460800
monitor_port = /dev/cu.usbserial-10
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time

build_flags =
    -DARDUINO_INKPLATE10
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

lib_deps =
    https://github.com/SolderedElectronics/Inkplate-Arduino-library.git
    bblanchon/ArduinoJson@^7.2.0
